development:
  adapter: postgresql
  encoding: unicode
  database: stat_streak_dev
  pool: 5
  username: Jerel
  password:

test: 
  adapter: postgresql
  encoding: unicode
  database: stat_streak_test
  pool: 5
  username: Jerel 
  password:
